name: Lint C++ Code

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python (for cpplint)
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install linters
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format
          pip install cpplint

      - name: Run cpplint
        run: |
          echo "Running cpplint..."
          cpplint --recursive .

      - name: Run clang-format check
        run: |
          echo "Checking formatting with clang-format..."
          find . -name "*.cpp" -o -name "*.h" | xargs clang-format -i

      - name: Commit & Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: auto-fix lint issues"
          branch: ${{ github
