name: Lint & Auto-Fix

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Black
        run: pip install black

      - name: Run Black (auto-fix)
        run: black . --line-length 88

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Prettier & ESLint
        run: npm install --global prettier eslint

      - name: Run Prettier (auto-fix)
        run: prettier --write "**/*.{js,ts,json,md}"

      - name: Run ESLint (auto-fix)
        run: eslint . --ext .js,.ts --fix || true

      - name: Commit & Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: auto-fix lint issues"
          branch: ${{ github.ref_name }}
